# Generated by Django 4.1.1 on 2022-10-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0004_remove_friends_current_user_remove_friends_users_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="episodios",
            field=models.PositiveIntegerField(),
        ),
        migrations.RemoveField(
            model_name="anime",
            name="generos",
        ),
        migrations.AddField(
            model_name="anime",
            name="generos",
            field=models.ManyToManyField(to="anime.generos"),
        ),
    ]
