# Generated by Django 4.1.1 on 2022-10-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0005_alter_anime_episodios_remove_anime_generos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anime",
            name="logo",
            field=models.URLField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="anime",
            name="trailer",
            field=models.URLField(unique=True),
        ),
    ]
