# Generated by Django 4.1.1 on 2022-10-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0006_anime_logo_alter_anime_trailer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="logo",
            field=models.URLField(),
        ),
    ]
