# Generated by Django 4.1.1 on 2022-10-22 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0007_alter_anime_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anime",
            name="generos",
        ),
        migrations.AddField(
            model_name="anime",
            name="generos",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="anime.generos",
            ),
            preserve_default=False,
        ),
    ]
