# Generated by Django 4.1.1 on 2022-10-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0008_remove_anime_generos_anime_generos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anime",
            name="generos",
        ),
        migrations.AlterField(
            model_name="generos",
            name="genero",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name="anime",
            name="generos",
            field=models.ManyToManyField(to="anime.generos"),
        ),
    ]
