# Generated by Django 4.1.1 on 2022-10-23 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0009_remove_anime_generos_alter_generos_genero_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anime",
            name="generos",
        ),
        migrations.AddField(
            model_name="anime",
            name="generos",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="anime.generos",
            ),
            preserve_default=False,
        ),
    ]
