# Generated by Django 4.1.1 on 2022-10-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0010_remove_anime_generos_anime_generos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anime",
            name="generos",
        ),
        migrations.AddField(
            model_name="anime",
            name="generos",
            field=models.ManyToManyField(to="anime.generos"),
        ),
    ]
