# Generated by Django 4.1.1 on 2022-10-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0013_alter_anime_anime_alter_anime_trailer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anime",
            name="trailer",
        ),
        migrations.AlterField(
            model_name="anime",
            name="logo",
            field=models.CharField(max_length=500),
        ),
    ]
