# Generated by Django 4.1.1 on 2022-10-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0016_remove_otaku_path_image_alter_anime_anime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="otaku",
            name="path_image",
            field=models.CharField(
                default="anime/static/anime/images/default-pfp-18.jpg", max_length=30
            ),
        ),
    ]
