# Generated by Django 4.1.1 on 2022-10-27 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("anime", "0017_otaku_path_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friends",
            name="friends",
        ),
        migrations.AddField(
            model_name="friends",
            name="following",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="friends",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="otaku",
            name="path_image",
            field=models.CharField(max_length=30),
        ),
    ]
